#include "AbioticFixation.hpp"
#include "Henry.hpp"
#include "Impacts.hpp"
#include "CometDelivery.hpp"
#include "CrustAlteration.hpp"
#include "Subduction.hpp"
#include "FreundlichAdsorption.hpp"
#include "Volcanism.hpp"
