{
    Reservoirs:
    {
        Atmosphere:
        {
            InitMasses: [4e21, 0, 0],
            Processes: ["Impacts", "CometDelivery", "AbioticFixation"]
        },
        Oceans:
        {
            InitMasses: [0, 0, 0],
            Processes: ["CrustAlteration", "Henry"]
        },
        OCrust:
        {
            InitMasses: [0, 0, 0],
            Processes: ["Subduction"]
        },
        UMantle:
        {
            InitMasses: [0, 0, 0],
            Processes: ["Volcanism"]
        },
        LMantle:
        {
            InitMasses: [0, 0, 0],
            Processes: ["Convection"]
        }
    },

    Henry: {
        H0: 6.1e-6,
        V0: 1.3e18
    },

    Impacts: {
        tau: 0.15e9,
        F0: 4.7e8,
        F1: 4.7e11
    },

    AbioticFixation: {
        M_REF: 4e21,
        F_NOx: 4.0e10,
        F_NH3: 1.6e7
    },

    CometDelivery: {
        tau: 0.15e9,
        F0: 2.4e5,
        F1: 2.4e8
    },

    CrustAlteration: {
        tau: 1e9, 
        F0: 1e-7,
        F1: 3e-7,
        F_NOx: 1,
        F_N2: 1e-3
    },

    Convection: {
        tau: 1e9, 
        F0: 1e-8,
        F1: 3e-8,
    },

    Subduction: {
        tau: 200e6, 
        VCrust: 369e15
    },

    Volcanism: {
        F_arc: 5,
        F_MORB: 20,
        F_hotspot: 2.5, 
        density: 2800,
        scaling: 1e21
    },

    OutFolder: "output",
    Tmax: 4500e6,
    Output: 25e6,
    Timestep: 10e3,
    Debug: false
}
