{
    Reservoirs:
    {
        Atmosphere:
        {
            InitMasses: [7e17, 0, 0],
        },
        Oceans:
        {
            InitMasses: [1e16, 1e17, 1.9e17],
        },
        OCrust:
        {
            InitMasses: [0, 0, 1e17],
        },
        UMantle:
        {
            InitMasses: [0, 0, 199e17],
        },
        LMantle:
        {
            InitMasses: [0, 0, 119e17],
        },
        CCrust:
        {
            InitMasses: [0, 0, 10e17],
        }
    },

    Processes:
    [
        "AbioticFixation",
        "FreundlichAdsorption",
        "HydrothermalCirculation",
        "Subduction",
        "Volcanism",
        "Convection",
        "Erosion",
        "Henry",
    ],

    Erosion: {
        uniform_growth: false,
        alpha: 5e-4,
    },

    Henry: {
        H0: 6.1e-6,
        V0: 1.3e18,
        change: 0,
        evolution: true
    },

    BioticContribution: {
        efficiency: true,
        dbio: 1e8,
        onset: 1e9,
        EA: 0,
        ED: 0,
        const_E6: true,
        E6i: 0.1,
        MMAX: 1e15
    },

    Impacts: {
        M_REF: 4e18,
        tau: 0.15e9,
        F0: 4.7e6,
        F1: 4.7e9,
    },

    AbioticFixation: {
        M_REF: 4e18,
        Fi_NOx: 4.0e10,
        Fi_NH3: 1.6e7,
        Ff_NOx: 2.6e6,
        Ff_NH3: 1.0e3,
        tau: 0.1e9,
        goe: 100e9
    },

    CometDelivery: {
        tau: 0.15e9,
        F0: 2.4e5,
        F1: 2.4e8
    },

    FreundlichAdsorption: {
        VSed: 6.1e17,
        rhoSed: 1700,
        Kf: 1e-3
    },

    HydrothermalCirculation: {
        tau: 100e9, 
        F0: 1e-7,
        F1: 3e-7,
        F_NOx: 1,
        F_N2: 1e-3
    },

    Convection: {
        tau: 100e9, 
        F0: 1e-8,
        F1: 3e-8,
    },

    Subduction: {
        accretion: 0.05,
        tau: 100e6, 
        VCrust: 369e15
    },

    Volcanism: {
        F_arc: 5,
        F_MORB: 20,
        F_hotspot: 2.5, 
        density: 2800,
        scaling: 1e21
    },

    atm_ox: 0.2,
    man_ox: 0.2,
    OutFolder: "output",
    Tmax: 4500e6,
    Output: 10e6,
    Timestep: 5e3,
    Debug: False
}
