{
    Reservoirs:
    {
        Atmosphere:
        {
            InitMasses: [4e21, 0, 0],
            Processes: ["Lightning", "Impacts", "AbioticFixation"]
        },
        Oceans:
        {
            InitMasses: [0, 0, 0],
            Processes: ["CrustAlteration", "CometDelivery"]
        },
        CCrust:
        {
            InitMasses: [0, 0, 0],
            Processes: []
        },
        OCrust:
        {
            InitMasses: [0, 0, 0],
            Processes: ["Subduction"]
        },
        UMantle:
        {
            InitMasses: [0, 0, 0],
            Processes: ["UMDegassing"]
        },
        LMantle:
        {
            InitMasses: [0, 0, 0],
            Processes: ["LMDegassing"]
        }
    },

    Lightning: {
        tau: 20e9,
        F0: 1e12
    },

    Impacts: {
        tau: 0.15e9,
        F0: 4.7e8,
        F1: 4.7e11
    },

    AbioticFixation: {
        M_REF: 4e21,
        F_NOx: 4.0e10,
        F_NH3: 1.6e7
    },

    CometDelivery: {
        tau: 0.15e9,
        F0: 2.4e5,
        F1: 2.4e8
    },

    CrustAlteration: {
        tau: 1e9, 
        F0: 1e-5,
        F1: 3e-5,
        F_NOx: 1,
        F_N2: 1e-3
    },

    Subduction: {
        tau: 20e9, 
        F0: 1e11
    },

    UMDegassing: {
        tau: 20e9, 
        F0: 1e11,
        speciation: 0.5,
        subaqueous: 0.25
    },

    LMDegassing: {
        tau: 20e9, 
        F0: 1e11,
        subaqueous: 0.05
    },

    OutFolder: "output",
    Tmax: 4500e6,
    Output: 25e6,
    Timestep: 10e3,
    Debug: false
}
