{
    Reservoirs:
    {
        Atmosphere:
        {
            InitMasses: [4e21, 0, 0],
            Processes: ["Lightning", "Impacts"]
        },
        Oceans:
        {
            InitMasses: [0, 0, 0],
            Processes: ["CrustAlteration"]
        },
        CCrust:
        {
            InitMasses: [0, 0, 0],
            Processes: []
        },
        OCrust:
        {
            InitMasses: [0, 0, 0],
            Processes: ["Subduction"]
        },
        UMantle:
        {
            InitMasses: [0, 0, 0],
            Processes: ["UMDegassing"]
        },
        LMantle:
        {
            InitMasses: [0, 0, 0],
            Processes: ["LMDegassing"]
        }
    },

    Lightning: {
        tau: 20e9,
        F0: 1e12
    },

    Impacts: {
        tau: 1e6,
        F0: 1e14
    },

    CrustAlteration: {
        tau: 1e9, 
        F0: 1e12
    },

    Subduction: {
        tau: 20e9, 
        F0: 1e11
    },

    UMDegassing: {
        tau: 20e9, 
        F0: 1e11,
        speciation: 0.5,
        subaqueous: 0.25
    },

    LMDegassing: {
        tau: 20e9, 
        F0: 1e11,
        subaqueous: 0.05
    },

    OutFolder: "output",
    Tmax: 4500e6,
    Output: 25e6,
    Timestep: 10e3,
    Debug: false
}
